DIALECT = 'mysql'
DRIVER = 'pymysql'
USERNAME = 'root'
PASSWORD = '20000520'
HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'flask_demo'
SECRET_KEY = 'TPmi4aLWRbyVq8zu9v82dWYW1'
SQLALCHEMY_DATABASE_URI = "{}+{}://{}:{}@{}:{}/{}?charset=utf8".format(DIALECT, DRIVER, USERNAME, PASSWORD, HOST, PORT,DATABASE)